### ISSUE TITLE
프로젝트 리뷰

### ISSUE THREAD

**Issue by crongro** [codesquad-member-2020/signup-8#23]
이슈리스트가 많네요! feature(task)를 잘 도출하신 듯.  아직 close 된 건 별로 없어서 안타깝;; ㅎ

이슈에 등록한 내용보니 아무 세세하게 하위태스크를 만들었네요. 힘들지 않았나요? 이정도로 하면 좋긴하죠.
👍 

단위 기능이 완료되면 PR을 보내고 merge하면 좋겠습니다.(하고 계시지만 1개 있길래 )

enhancement 를 사용했는데 이건 사실 '기능개선'차원에서 많이 쓰이고, 새로운 feature 나 task labe을 만들어서 활용해도 될 거 같네요.

projects 활용도 좋아보이네요.  be,fe,ios 나눠서 하는 것도 좋은 방법같아요.
칸반보드라는 게 뭔지 한번 보세요. 지금 project처럼 비슷한 방식으로 프로젝트를 관리하곤 합니다.

짧은 피드백 남겼어요.
잘하고 계시니 화이팅하고 마무리 잘 해보죠!

**Comment by choisohyun** [comment]
순서가 뒤바뀐채 이것저것 같이 하고 있습니다.. PR도 어서 보내보도록 하겠습니다 감사합니다~!

**Comment by crongro** [comment]
- 덩그러니 fe, iOS라고만 되어 있는 이름의 branch는 이름이 어색하네요. feature인지 뭔지 표현을 해주세요~
- 모두다 커밋단위가 좋고, 커밋규칙을 잘 지키시는 듯 
- Projects TODO에서 변경업데이트를 잘 못지킨 것도 보이네요. 이런거 지키는게 원래 어렵습니다. 하지만 동료들과 함께 하면 이런걸 지키는 것이 좋은 커뮤니케이션 스킬이기도 해요~! 
- wiki를 문서의 접점역할로 한 것은 좋습니다. 
- 이런문서도 좋고요 (https://github.com/codesquad-memeber-2020/signup-8/wiki/%5BBE%5D-%EC%84%A4%EA%B3%84)

**Comment by 1Consumption** [comment]
fe, be, iOS라는 이름은 각 클래스의 dev 브랜치였는데 표시를 안했네요! 조금 더  신경쓰겠습니다.
